parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 6
  sourceType:  module
  ecmaFeatures:
    jsx:                          true
    experimentalObjectRestSpread: true

env:
  browser: true
  es6:     true

globals:
  global: true

plugins:
  - '@typescript-eslint'

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint

rules:
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-empty-interface': 'off'
  '@typescript-eslint/no-empty-function': 'warn'

settings:
  react:
    version: detect
